# Generated by Django 3.2.7 on 2021-09-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country_field',
            new_name='Country_field',
        ),
        migrations.RenameField(
            model_name='city',
            old_name='population',
            new_name='Population',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name',
        ),
        migrations.AddField(
            model_name='city',
            name='District',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='Name',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='State',
            field=models.CharField(default='---', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='are_you_Student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='city',
            name='field',
            field=models.CharField(default='Read only field', max_length=30),
        ),
        migrations.AddField(
            model_name='city',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
