# Generated by Django 3.2.7 on 2021-09-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210928_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
