# Generated by Django 3.2.7 on 2021-09-28 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_city_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='District',
        ),
        migrations.RemoveField(
            model_name='city',
            name='Population',
        ),
        migrations.RemoveField(
            model_name='city',
            name='State',
        ),
        migrations.RemoveField(
            model_name='city',
            name='are_you_Student',
        ),
        migrations.RemoveField(
            model_name='city',
            name='field',
        ),
    ]
