# Generated by Django 3.2.7 on 2021-09-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210928_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='Country_field',
        ),
        migrations.AlterField(
            model_name='city',
            name='Name',
            field=models.CharField(default='Mumbai', max_length=30),
        ),
    ]
